# Generated by Django 5.2.5 on 2025-09-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='file_shared',
            field=models.FileField(blank=True, null=True, upload_to='groupchat_file'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='image_shared',
            field=models.ImageField(blank=True, null=True, upload_to='group_chat_image'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_shared',
            field=models.FileField(blank=True, null=True, upload_to='personalchat_file'),
        ),
        migrations.AddField(
            model_name='message',
            name='image_shared',
            field=models.ImageField(blank=True, null=True, upload_to='personal_chat_image'),
        ),
    ]
