# Generated by Django 5.2.5 on 2025-09-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_groupmessage_file_shared_groupmessage_image_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default='no_name', max_length=100),
        ),
    ]
