# Generated by Django 5.2.5 on 2025-09-03 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='group_member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='group_member', to='chat.groupmember'),
        ),
    ]
