# Generated by Django 5.2.5 on 2025-09-03 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_groupmessage_group_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='group_member',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='chat.groupmember'),
        ),
    ]
