# Generated by Django 5.2.5 on 2025-09-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_groupmessage_group_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='no_name', max_length=200, unique=True),
        ),
    ]
