# Generated by Django 5.2.5 on 2025-09-04 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_group_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='group_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='chat.groupmember'),
        ),
    ]
