# Generated by Django 5.2.7 on 2025-10-09 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_groupmessage_group_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='file_shared',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='image_shared',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_shared',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image_shared',
        ),
        migrations.CreateModel(
            name='AttachmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='group_image')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='file_videos')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.group')),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='group_image')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='file_videos')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
            ],
        ),
    ]
