# Generated by Django 5.2.7 on 2025-10-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_groupmessage_file_shared_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachmentpersonal',
            old_name='file',
            new_name='files_i',
        ),
    ]
