# Generated by Django 5.2.7 on 2025-10-10 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_rename_file_attachmentpersonal_files_i'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentpersonal',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
    ]
