# Generated by Django 5.2.7 on 2025-10-10 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_attachmentpersonal_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentpersonal',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message'),
        ),
    ]
