# Generated by Django 5.2.7 on 2025-10-10 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_attachmentpersonal_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachmentgroup',
            old_name='file',
            new_name='files_i',
        ),
        migrations.AddField(
            model_name='attachmentgroup',
            name='group_msg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_attachments', to='chat.groupmessage'),
        ),
        migrations.AlterField(
            model_name='attachmentgroup',
            name='group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_name_att', to='chat.group'),
        ),
    ]
